project = "helloworld"

# Create archive aliases (copies) for base archive filenames
# which contains the string on the left, e.g.
#  { "linux-64bit" = "linux-amd64" }.
#
# The common use case is to to preserve some backward compability on name changes,
# the example above is taken from Hugo.
# You can include any extension in the above to limit this to e.g. only .deb archives.
archive_alias_replacements = {}

# Go settings can be set on any of Project > Build.
# See Build settings for merge rules.
[go_settings]
    #  go_proxy will be used to set GOPROXY when running Go.
    # It will default to 'https://proxy.golang.org' if not set.
    #
    #  See https://proxy.golang.org/ for more information.
    go_proxy = "https://proxy.golang.org"
    go_exe   = "go"

# Build settings can be set on any of Project > Build > Goos > Goarch.
# Zero values (empty strings, 0 numbers) and nil slices/maps wil inherit values from the nearest non-zero value above for a key.
# Empty slices and maps will stay empty (e.g. `env = []`)
[build_settings]
    binary  = "helloworld"
    flags   = ["-buildmode", "exe"]
    env     = ["CGO_ENABLED=0"]
    ldflags = ""

# Archive settings can be set on any of Project > Archive.
# Follows the same merge rules as Build settings.
[archive_settings]
    name_template = "{{ .Project }}_{{ .Tag | trimPrefix `v` }}_{{ .Goos }}-{{ .Goarch }}"
    # Extra, as in: In addition to the binary.
    extra_files = [
        { source_path = "README.md", target_path = "README.md" },
        { source_path = "LICENSE", target_path = "LICENSE" },
    ]
    [archive_settings.type]
        format    = "tar.gz"
        extension = ".tar.gz"

[release_settings]
    name             = "${HUGORELEASER_TAG}"
    type             = "github"
    repository       = "helloworld"
    repository_owner = "bep"

    draft      = true
    prerelease = false

    [release_settings.release_notes_settings]
        # Use Hugoreleaser's autogenerated release notes.
        generate = true
        # Enable this to use GitHub's autogenerated release notes.
        generate_on_host = false

        # Set this if you have release notes file ready to use.
        filename = ""

        # A custom template filename for Hugoreleaser's autogenerated release notes.
        # Will fall back to the default if not set.
        template_filename = ""

        # Collapse relases with < 10 changes below one title.
        short_threshold = 10
        short_title     = "What's Changed"

        groups = [
            { regexp = "snapcraft:|Merge commit|Squashed", ignore = true },
            { title = "Bug fixes", regexp = "fix", ordinal = 20 },
            { title = "Dependency Updates", regexp = "deps", ordinal = 30 },
            { title = "Documentation", regexp = "doc", ordinal = 40 },
            { title = "Improvements", regexp = ".*", ordinal = 10 },
        ]

[[builds]]
    path = "unix"
    [[builds.os]]
        goos = "linux"
        [[builds.os.archs]]
            goarch = "amd64"
[[builds]]
    path = "macos"
    [[builds.os]]
        goos = "darwin"
        [[builds.os.archs]]
            goarch = "universal"
[[builds]]
    path = "windows"
    [[builds.os]]
        goos = "windows"
        [builds.os.build_settings]
            binary = "helloworld.exe"
        [[builds.os.archs]]
            goarch = "amd64"
[[archives]]
    paths = ["builds/unix/**"]
[[archives]]
    paths = ["builds/macos/**"]
[[archives]]
    paths = ["builds/windows/**"]
    [archives.archive_settings]
        [archives.archive_settings.type]
            format    = "zip"
            extension = ".zip"

[[releases]]
    paths = ["archives/**"]
    path  = "myrelease"
